/**
 * Time the two front-end budgets §12 states, and print them as JSON.
 *
 *   node tests/perf/budgets.js <payload.json> <mandate.json>
 *
 * §12 budgets mandate feasibility at under 100 ms and the holdings table's sort and
 * filter at under 50 ms over 500 rows. Both are client-side — the first because that
 * is why `feasibility.js` exists at all rather than calling the server — so both have
 * to be measured here rather than in pytest.
 *
 * The payload is generated by the Python side and handed over, so the two suites
 * measure the same pipeline rather than two notions of one.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const feasibility = require(path.join(ROOT, 'web', 'js', 'feasibility.js'));
const controls = require(path.join(ROOT, 'web', 'js', 'controls.js'));

const REPEATS = 20;

function median(values) {
  const sorted = values.slice().sort(function (a, b) { return a - b; });
  const middle = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[middle] : (sorted[middle - 1] + sorted[middle]) / 2;
}

function timed(run) {
  const samples = [];
  for (let i = 0; i < REPEATS; i++) {
    const started = process.hrtime.bigint();
    run();
    samples.push(Number(process.hrtime.bigint() - started) / 1e6);
  }
  return { medianMs: median(samples), worstMs: Math.max.apply(null, samples) };
}

/** §12: the whole mandate footer, recomputed from scratch on every control change. */
function mandateFeedback(payload, mandate) {
  let answer = null;
  const timing = timed(function () {
    answer = feasibility.feasibility(payload, mandate, { lockedIds: [], excludedIds: [] });
  });
  return Object.assign(timing, {
    projects: payload.projects.length,
    eligible: answer.eligibleCount,
  });
}

/**
 * §12: sorting and filtering the holdings table at 500 rows.
 *
 * `web/js/table.js` is #11's and does not exist yet, so the *algorithm* cannot be
 * timed. What can be, and what this measures, is the per-row work 1D's `holdingsTable`
 * factory does on every render of every row — the label lookups, the DSCR breach test,
 * the row class and the screen-reader name — plus a comparator sort over the same rows
 * on the field the header state names. That is the bulk of what a re-sort costs; the
 * `table.js` line below reports whether the rest of it exists yet, so this result can
 * never be mistaken for a measurement of code that is not written.
 */
function holdingsTable(rows) {
  const table = controls.holdingsTable({ dscrFloor: 1.25 });
  table.rows = rows;

  const timing = timed(function () {
    const sorted = table.rows.slice().sort(function (a, b) {
      const left = a[table.field];
      const right = b[table.field];
      if (left === right) return 0;
      const ascending = table.direction === 'ascending';
      return (left < right ? -1 : 1) * (ascending ? 1 : -1);
    });
    const visible = sorted.filter(function (row) { return row.selected !== false; });
    visible.forEach(function (row) {
      table.technologyLabel(row);
      table.stageLabel(row);
      table.lockMark(row);
      table.lockName(row);
      table.rowClass(row);
      table.dscrBreached(row);
      table.dscrClass(row);
      table.dscrMark(row);
      table.dscrNote(row);
    });
  });

  return Object.assign(timing, {
    rows: rows.length,
    field: table.field,
    tableJsPresent: fs.existsSync(path.join(ROOT, 'web', 'js', 'table.js')),
  });
}

/** 500 holdings rows in the §5.4 shape, derived from the payload's own projects. */
function holdingsFrom(payload, count) {
  const source = payload.projects;
  const rows = [];
  for (let i = 0; i < count; i++) {
    const project = source[i % source.length];
    rows.push({
      id: 'H' + String(i).padStart(4, '0'),
      name: project.name,
      technology: project.technology,
      stage: project.stage,
      countryCode: project.countryCode,
      capacityMw: project.capacityMw,
      equity_m: project.equity_m,
      equityIrr: project.equityIrr === undefined ? 0.1 + (i % 50) / 500 : project.equityIrr,
      minDscr: project.minDscr,
      locked: i % 17 === 0,
      selected: i % 3 !== 0,
    });
  }
  return rows;
}

function main(argv) {
  if (argv.length !== 2) {
    process.stderr.write('usage: node budgets.js <payload.json> <mandate.json>\n');
    return 2;
  }
  const payload = JSON.parse(fs.readFileSync(argv[0], 'utf8'));
  const mandate = JSON.parse(fs.readFileSync(argv[1], 'utf8'));
  process.stdout.write(JSON.stringify({
    node: process.version,
    mandateFeedback: mandateFeedback(payload, mandate),
    holdingsTable: holdingsTable(holdingsFrom(payload, 500)),
  }) + '\n');
  return 0;
}

if (require.main === module) process.exitCode = main(process.argv.slice(2));
