/**
 * Every colour pairing the pages actually render, measured — spec §12's 4.5:1.
 *
 * tests/contrast.test.js checks the twenty-eight role pairs the design system
 * defines. This answers the other half of the question: not "is every role the
 * system defines legible" but "is every pair the markup actually produces legible".
 * A role nobody uses cannot fail in front of a user; a pair nobody wrote down can —
 * and `accent-700` on `highlight`, which the tiles render, was in neither list.
 *
 * The pages are walked with the holdings rows populated and both overlays open,
 * because a pairing that only appears inside a drawer is still one a user reads.
 *
 * The table in docs/decisions.md is generated by tests/tools/contrast-audit.js and
 * asserted here to still match — the arrangement tools/splice-nav.mjs and
 * nav.test.js already use, so the document cannot drift from the markup.
 */
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { auditRows, renderTable } = require('./helpers/audit.js');
const { ratio, inherited, parse, over, isHidden, C } = require('./helpers/contrast.js');
const { PAGES, loadPage } = require('./helpers/page.js');
const { status } = require('../js/controls.js');

const DECISIONS = path.resolve(__dirname, '..', '..', 'docs', 'decisions.md');
const HEADING = '#### The contrast audit';

let cached = null;
const rows = async () => { cached = cached || await auditRows(); return cached; };

test('every pairing the pages render clears its WCAG floor', async () => {
  const audited = await rows();
  assert.ok(audited.length >= 12, `only ${audited.length} pairings found; the walk is not working`);

  const failing = audited.filter((r) => r.ratio < r.need).map((r) =>
    `${r.fg} on ${r.bg} (${r.what}) is ${r.ratio.toFixed(2)}:1, needs ${r.need}:1`);
  assert.deepEqual(failing, [],
    'Move the role to a darker step on the ladder rather than inventing a colour — '
    + 'the ladder is fixed by issue #5 and A-20 records why.');
});

test('no colour is hard-coded outside the ladder', async () => {
  const arbitrary = (await rows()).filter((r) => r.arbitrary);
  assert.deepEqual(arbitrary, [],
    'a literal colour in a class bypasses the ladder, the audit and contrast.test.js');
});

test('the audit table in docs/decisions.md is the one this recomputes', async () => {
  const doc = fs.readFileSync(DECISIONS, 'utf8');
  const from = doc.indexOf(HEADING);
  assert.ok(from > 0, `docs/decisions.md must carry a "${HEADING}" section`);

  const after = doc.slice(from);
  const start = after.indexOf('| Foreground |');
  const end = after.indexOf('\n\n', start);
  const recorded = after.slice(start, end === -1 ? undefined : end).trim();

  assert.equal(recorded, renderTable(await rows()),
    'the recorded table no longer matches the markup. Re-run:\n'
    + '  node tests/tools/contrast-audit.js\n'
    + 'and paste the result under the heading in docs/decisions.md.');
});

/**
 * The counterpart to excluding decoration from the walk above. A status mark is
 * `aria-hidden` — it is a duplicate of the word beside it, as far as a screen
 * reader is concerned — but it is the *only* signal a sighted reader gets, so it
 * cannot be allowed to hide behind the decoration exemption.
 */
test('every status mark on a page is legible, decoration exemption notwithstanding', async () => {
  const MARKS = new Set(Object.values(status.MARK).filter(Boolean));
  const dim = [];

  for (const page of PAGES) {
    const dom = await loadPage(page);
    const d = dom.window.document;
    for (const el of d.querySelectorAll('[aria-hidden="true"]')) {
      const text = el.textContent.trim();
      if (!MARKS.has(text) || isHidden(el)) continue;
      const fg = inherited(el, 'text', d) || { name: 'text', parsed: parse(C.text) };
      const bg = inherited(el, 'bg', d) || { name: 'bg', parsed: parse(C.bg) };
      const ground = over(bg.parsed, C.bg);
      const r = ratio(over(fg.parsed, ground), ground);
      if (r < 4.5) dim.push(`${page}: "${text}" in ${fg.name} on ${bg.name} is ${r.toFixed(2)}:1`);
    }
    dom.window.close();
  }
  assert.deepEqual(dim, [],
    'a mark is the whole non-colour channel for a sighted reader; it has to be readable');
});

test('the only text below the floor is decoration that carries nothing', async () => {
  const offenders = [];
  for (const page of PAGES) {
    const dom = await loadPage(page);
    const d = dom.window.document;
    for (const el of d.querySelectorAll('[aria-hidden="true"]')) {
      const text = el.textContent.trim();
      if (!text || isHidden(el)) continue;
      const fg = inherited(el, 'text', d) || { name: 'text', parsed: parse(C.text) };
      const bg = inherited(el, 'bg', d) || { name: 'bg', parsed: parse(C.bg) };
      const ground = over(bg.parsed, C.bg);
      if (ratio(over(fg.parsed, ground), ground) >= 4.5) continue;
      // The stepper's em-dash separators: punctuation between three step labels,
      // hidden from assistive technology, conveying nothing that is not adjacent.
      const separator = el.tagName === 'LI' && el.closest('ol[aria-label="Progress"]');
      if (!separator) offenders.push(`${page}: "${text.slice(0, 40)}" in ${fg.name} on ${bg.name}`);
    }
    dom.window.close();
  }
  assert.deepEqual(offenders, [],
    'WCAG 1.4.3 exempts pure decoration, and this is the whole list of what claims it. '
    + 'Anything new here is either a real failure or owes a reason in docs/decisions.md.');
});
