/**
 * Populates web/fonts/, web/public/ and web/vendor/ from sources that are already
 * in the repository or already installed, so a build never reaches the network.
 *
 * Fonts and the world atlas come out of `Portfolio Optimiser (standalone).html`,
 * the design-mockup bundle: its resources are gzip+base64 blobs keyed by UUID in a
 * <script type="__bundler/manifest"> tag, and its @font-face rules map each UUID to a
 * family/weight/subset. Taking them from there rather than from Google Fonts keeps the
 * faces byte-identical to the mockup they were designed against (Barlow is OFL).
 *
 * Run: npm run vendor
 */
import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import { fileURLToPath } from 'node:url';

const WEB = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const REPO = path.resolve(WEB, '..');
const BUNDLE = path.join(REPO, 'Portfolio Optimiser (standalone).html');

/* The faces the design system actually selects. Barlow Condensed 400/500 and Barlow 700
   are declared in the mockup but never used; vietnamese subsets are dead weight for a
   European pipeline, so only latin and latin-ext are carried. */
const FACES = [
  ['Barlow', 400], ['Barlow', 500], ['Barlow', 600],
  ['Barlow Condensed', 600], ['Barlow Condensed', 700],
];
const SUBSETS = ['latin', 'latin-ext'];

function readBundle() {
  const html = fs.readFileSync(BUNDLE, 'utf8');
  const template = JSON.parse(
    html.match(/<script type="__bundler\/template">\n([\s\S]*?)\n {2}<\/script>/)[1]);
  const manifest = JSON.parse(
    html.match(/<script type="__bundler\/manifest">([\s\S]*?)<\/script>/)[1]);
  return { html, template, manifest };
}

function resource(manifest, uuid) {
  const entry = manifest[uuid];
  if (!entry) throw new Error(`bundle has no resource ${uuid}`);
  const bytes = Buffer.from(entry.data, 'base64');
  return entry.compressed ? zlib.gunzipSync(bytes) : bytes;
}

/** family|weight|subset -> { uuid, unicodeRange } straight out of the mockup's @font-face rules. */
function fontIndex(template) {
  const index = new Map();
  const rule = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([\s\S]*?)\}/g;
  let m;
  while ((m = rule.exec(template))) {
    const [, subset, body] = m;
    const family = (body.match(/font-family:\s*'([^']+)'/) || [])[1];
    const weight = (body.match(/font-weight:\s*(\d+)/) || [])[1];
    const uuid = (body.match(/url\("([^"]+)"\)/) || [])[1];
    const unicodeRange = (body.match(/unicode-range:\s*([^;]+);/) || [])[1];
    const key = `${family}|${weight}|${subset}`;
    if (family && weight && uuid && !index.has(key)) {
      index.set(key, { uuid, unicodeRange: unicodeRange.trim() });
    }
  }
  return index;
}

const slug = (family, weight, subset) =>
  `${family.toLowerCase().replace(/ /g, '-')}-${weight}-${subset}.woff2`;

function writeFonts(template, manifest) {
  const index = fontIndex(template);
  const faces = [];
  for (const [family, weight] of FACES) {
    for (const subset of SUBSETS) {
      const key = `${family}|${weight}|${subset}`;
      const hit = index.get(key);
      if (!hit) throw new Error(`bundle has no @font-face for ${key}`);
      const file = slug(family, weight, subset);
      fs.writeFileSync(path.join(WEB, 'fonts', file), resource(manifest, hit.uuid));
      faces.push({ family, weight, file, unicodeRange: hit.unicodeRange });
    }
  }
  return faces;
}

/** The @font-face block for src/input.css, so the CSS and the files can never drift apart. */
function fontFaceCss(faces) {
  return faces.map(f => `@font-face {
  font-family: '${f.family}';
  font-style: normal;
  font-weight: ${f.weight};
  font-display: swap;
  src: url('../fonts/${f.file}') format('woff2');
  unicode-range: ${f.unicodeRange};
}`).join('\n\n');
}

function writeAtlas(manifest, html) {
  const extResources = JSON.parse(
    html.match(/<script type="__bundler\/ext_resources">\s*([\s\S]*?)\s*<\/script>/)[1]);
  const entry = extResources.find(r => r.id === 'worldAtlas');
  if (!entry) throw new Error('bundle has no worldAtlas resource');

  const atlas = JSON.parse(resource(manifest, entry.uuid).toString('utf8'));
  if (atlas.type !== 'Topology' || !atlas.objects.countries) {
    throw new Error('worldAtlas is not the expected countries topology');
  }
  fs.writeFileSync(path.join(WEB, 'public', 'countries-110m.json'), JSON.stringify(atlas));

  /* fetch() is blocked over file://, so the pages cannot read the .json from disk.
     This wrapper is the same data as a classic script, generated from the same source. */
  fs.writeFileSync(path.join(WEB, 'public', 'countries-110m.js'),
    '/* Generated by tools/vendor.mjs from countries-110m.json \u2014 do not edit.\n' +
    '   A classic-script form of the atlas, because fetch() cannot read file:// URLs. */\n' +
    'window.TerraFolio = window.TerraFolio || {};\n' +
    'window.TerraFolio.worldAtlas = ' + JSON.stringify(atlas) + ';\n');

  return atlas.objects.countries.geometries.length;
}

const VENDOR = [
  ['alpinejs/dist/cdn.min.js', 'alpine.min.js'],
  ['d3-array/dist/d3-array.min.js', 'd3-array.min.js'],
  ['d3-geo/dist/d3-geo.min.js', 'd3-geo.min.js'],
  ['topojson-client/dist/topojson-client.min.js', 'topojson-client.min.js'],
];

function writeVendor() {
  return VENDOR.map(([from, to]) => {
    const src = path.join(WEB, 'node_modules', from);
    if (!fs.existsSync(src)) throw new Error(`missing ${from} — run npm ci first`);
    fs.copyFileSync(src, path.join(WEB, 'vendor', to));
    return to;
  });
}

const { html, template, manifest } = readBundle();
const faces = writeFonts(template, manifest);
const countries = writeAtlas(manifest, html);
const vendored = writeVendor();

fs.writeFileSync(path.join(WEB, 'src', 'fonts.css'),
  '/* Generated by tools/vendor.mjs — do not edit. Imported by input.css. */\n\n' +
  fontFaceCss(faces) + '\n');

console.log(`fonts     ${faces.length} woff2 (${FACES.length} faces × ${SUBSETS.length} subsets)`);
console.log(`atlas     countries-110m.json + .js (${countries} geometries)`);
console.log(`vendor    ${vendored.join(', ')}`);
