// GENERATED by tools/extract_reference.mjs — do not edit.
//
// This file is ESM. The .mjs extension is deliberate: there is no package.json
// here, so a .js extension would leave the module classification to Node's
// syntax detection, which is version-dependent.
//
// The class body below is copied VERBATIM out of the `text/x-dc` script tag
// inside the __bundler/template payload of "Portfolio Optimiser (standalone).html"
// (sha256 bc4722f836d1274a4351c1c986f7661ae0ef399c5f915cad758dbce4f10a7463).  Only the wrapper is ours: the reference declares
// `class Component extends DCLogic` against a global base class, and we take
// that base as a parameter instead so the module is importable.
//
// Regenerate with: node tools/extract_reference.mjs

// `setInterval`/`clearInterval` are taken as parameters rather than read from
// the global scope: the reference's run() schedules its GA on a timer, and
// passing stubs here lets us drive that loop synchronously and deterministically
// without editing a character of the reference's own source.
/**
 * @param {Function} DCLogic base class supplying `this.props` and `this.setState`
 * @param {Function} setInterval captures the GA step function
 * @param {Function} clearInterval signals the GA has finished
 */
export function defineComponent(DCLogic, setInterval, clearInterval) {
  return class Component extends DCLogic {
  projects = this.buildPipeline();

  state = {
    screen: 'input',
    gen: 0, hist: [], best: null, popSize: 90, genTotal: 60,
    capital: 1200, target: 1500, solarShare: 0.45, hurdle: 11, hold: 10,
    countries: ['ES','PT','IT','GR','FR','DE','PL','RO','NL','DK','IE','SE','FI','UK'],
    stages: ['Greenfield','Ready-to-build','Construction'],
    minLev: 60, minDscr: 1.25, maxMerchant: 35, maxCountry: 35, maxProject: 15,
    codFrom: 2027, codTo: 2032, risk: 'Balanced',
    gridOnly: false, hedged: false, omOnly: false,
    locked: [], excluded: [],
    sortKey: 'irr', sortDir: -1,
    q: '', fCountry: 'All', fTech: 'All', fStage: 'All', showAll: false,
    drawer: null, exportOpen: false, hover: null, dirty: false, runRef: 'A-1'
  };

  // ── pipeline ───────────────────────────────────────────────────────────
  buildPipeline() {
    const raw = [
      ['Almonte Solar','ES',39.25,-6.52,'Solar','Ready-to-build',180,2028],
      ['Tierra Llana PV','ES',38.60,-5.90,'Solar','Greenfield',240,2030],
      ['Ebro Valley PV','ES',41.60,-0.90,'Solar','Construction',150,2027],
      ['Sierra Norte PV','ES',37.90,-4.80,'Solar','Ready-to-build',110,2029],
      ['Castilla Fields','ES',41.00,-4.50,'Solar','Greenfield',300,2031],
      ['Alqueva Solar','PT',38.20,-7.50,'Solar','Ready-to-build',95,2028],
      ['Algarve Sol','PT',37.20,-8.00,'Solar','Greenfield',130,2030],
      ['Guadiana Sol','PT',38.00,-7.90,'Solar','Construction',85,2027],
      ['Puglia Sole','IT',40.90,16.90,'Solar','Ready-to-build',85,2028],
      ['Sicilia Solare','IT',37.50,14.30,'Solar','Construction',120,2027],
      ['Maremma PV','IT',42.80,11.10,'Solar','Greenfield',70,2030],
      ['Thessaly Solar','GR',39.50,22.30,'Solar','Ready-to-build',105,2029],
      ['Peloponnese PV','GR',37.50,22.20,'Solar','Greenfield',90,2030],
      ['Attica Fields','GR',38.10,23.60,'Solar','Construction',65,2027],
      ['Occitanie Solaire','FR',43.60,1.40,'Solar','Ready-to-build',75,2029],
      ['Aquitaine PV','FR',44.80,-0.60,'Solar','Construction',60,2027],
      ['Lausitz Solarpark','DE',51.60,14.30,'Solar','Ready-to-build',140,2028],
      ['Bayern Süd PV','DE',48.40,11.60,'Solar','Greenfield',95,2030],
      ['Wielkopolska PV','PL',52.20,17.10,'Solar','Ready-to-build',80,2029],
      ['Dobrogea Solar','RO',44.40,28.30,'Solar','Greenfield',115,2030],
      ['Banat Solar','RO',45.80,21.20,'Solar','Ready-to-build',70,2029],
      ['Zeeland Zon','NL',51.50,3.90,'Solar','Construction',55,2027],
      ['Nordjylland Vind','DK',57.10,9.90,'Wind','Ready-to-build',90,2028],
      ['Jutland Ridge','DK',56.20,9.10,'Wind','Construction',60,2027],
      ['Connacht Wind','IE',53.70,-8.90,'Wind','Greenfield',110,2030],
      ['Kerry Highlands','IE',52.10,-9.50,'Wind','Ready-to-build',75,2029],
      ['Norrland Vind','SE',64.20,19.80,'Wind','Ready-to-build',200,2029],
      ['Västra Götaland','SE',58.20,12.60,'Wind','Greenfield',120,2030],
      ['Ostrobothnia Tuuli','FI',63.10,21.80,'Wind','Ready-to-build',180,2029],
      ['Lapland Ridge','FI',66.50,25.70,'Wind','Greenfield',160,2031],
      ['Schleswig Wind','DE',54.40,9.40,'Wind','Construction',100,2027],
      ['Eifel Höhen','DE',50.30,6.60,'Wind','Greenfield',65,2030],
      ['Pomorskie Wiatr','PL',54.20,18.00,'Wind','Ready-to-build',130,2029],
      ['Mazowsze Wind','PL',52.40,21.00,'Wind','Greenfield',90,2030],
      ['Bretagne Éolien','FR',48.20,-3.20,'Wind','Ready-to-build',70,2028],
      ['Champagne Crest','FR',48.90,4.30,'Wind','Construction',55,2027],
      ['Galicia Ventos','ES',42.90,-8.00,'Wind','Ready-to-build',95,2028],
      ['Aragón Wind','ES',41.30,-0.50,'Wind','Greenfield',140,2030],
      ['Alentejo Vento','PT',38.40,-8.20,'Wind','Ready-to-build',60,2029],
      ['Thrace Wind','GR',41.10,25.40,'Wind','Greenfield',85,2030],
      ['Apennine Ridge','IT',42.10,13.40,'Wind','Ready-to-build',50,2029],
      ['Groningen Wind','NL',53.30,6.80,'Wind','Construction',70,2027],
      ['Dobrogea Wind','RO',44.80,28.60,'Wind','Ready-to-build',150,2029],
      ['Scottish Borders','UK',55.50,-3.00,'Wind','Greenfield',130,2031],
      ['Hornsea Fringe','UK',53.90,1.80,'Offshore wind','Greenfield',400,2032],
      ['Kriegers Flak II','DK',55.10,13.00,'Offshore wind','Ready-to-build',350,2031],
      ['Borssele Extension','NL',51.70,3.00,'Offshore wind','Construction',300,2029],
      ['Baltica Nord','PL',54.80,17.50,'Offshore wind','Greenfield',450,2032]
    ];
    const cfSolar = {ES:0.245,PT:0.235,IT:0.215,GR:0.222,FR:0.172,DE:0.128,PL:0.118,NL:0.120,RO:0.158,IE:0.108,SE:0.108,FI:0.098,DK:0.118,UK:0.110};
    const cfWind  = {DK:0.402,IE:0.381,UK:0.362,SE:0.348,FI:0.336,DE:0.281,NL:0.318,PL:0.292,FR:0.268,ES:0.271,PT:0.262,IT:0.231,GR:0.283,RO:0.284};
    const merch   = {DE:73,ES:58,IT:92,FR:67,PL:80,NL:74,GR:84,SE:42,FI:45,DK:59,RO:80,IE:85,PT:56,UK:82};
    const names   = {ES:'Spain',PT:'Portugal',IT:'Italy',GR:'Greece',FR:'France',DE:'Germany',PL:'Poland',RO:'Romania',NL:'Netherlands',DK:'Denmark',IE:'Ireland',SE:'Sweden',FI:'Finland',UK:'United Kingdom'};
    const ccy     = {ES:'EUR',PT:'EUR',IT:'EUR',GR:'EUR',FR:'EUR',DE:'EUR',NL:'EUR',IE:'EUR',FI:'EUR',PL:'PLN',RO:'RON',DK:'DKK',SE:'SEK',UK:'GBP'};
    const iso3    = {ES:'ESP',PT:'PRT',IT:'ITA',GR:'GRC',FR:'FRA',DE:'DEU',PL:'POL',RO:'ROU',NL:'NLD',DK:'DNK',IE:'IRL',SE:'SWE',FI:'FIN',UK:'GBR'};

    return raw.map((r, i) => {
      const [name, cc, lat, lon, tech, stage, mw, cod] = r;
      const rnd = this.seeded(i * 97 + 13);
      const off = tech === 'Offshore wind';
      const solar = tech === 'Solar';
      const cf = off ? 0.49 + rnd() * 0.06 : solar ? cfSolar[cc] * (0.94 + rnd() * 0.12) : cfWind[cc] * (0.94 + rnd() * 0.12);
      const opexKw = off ? 78 + rnd() * 20 : solar ? 12 + rnd() * 4 : 42 + rnd() * 12;
      const capture = off ? 0.86 : solar ? 0.68 : 0.88;
      const riskBase = stage === 'Greenfield' ? 3.4 : stage === 'Ready-to-build' ? 2.2 : 1.5;
      const devRisk = Math.min(5, Math.max(1, Math.round((riskBase + (off ? 0.8 : 0) + rnd() * 1.2) * 10) / 10));
      const gridSecured = stage !== 'Greenfield' ? true : rnd() > 0.45;
      const omPartner = stage === 'Construction' ? true : rnd() > 0.35;
      const ppaShare = Math.round((stage === 'Construction' ? 0.65 + rnd() * 0.3 : stage === 'Ready-to-build' ? 0.45 + rnd() * 0.4 : 0.15 + rnd() * 0.5) * 100) / 100;
      const capturePrice = Math.round(merch[cc] * capture);
      const ppaPrice = Math.round(capturePrice * (0.86 + rnd() * 0.14));
      const ppaTenor = ppaShare > 0.05 ? [10, 12, 15, 15, 20][Math.floor(rnd() * 5)] : 0;
      const maxGear = stage === 'Construction' ? 0.75 : stage === 'Ready-to-build' ? 0.72 : 0.65;
      // Entry pricing: a developer sells at an EBITDA yield that reflects how de-risked
      // the asset is, so capex per kW falls out of the revenue case rather than the reverse.
      const deg0 = solar ? 0.005 : 0.002;
      const gen1 = mw * 8.760 * cf * (1 - deg0);
      const price1 = ppaTenor > 1 ? ppaShare * ppaPrice * 1.005 + (1 - ppaShare) * capturePrice * 1.021 : capturePrice * 1.021;
      const ebitda1 = gen1 * 1000 * price1 / 1e6 - mw * 1000 * opexKw * 1.021 / 1e6;
      const yieldTarget = (off ? 0.090 : stage === 'Greenfield' ? 0.116 : stage === 'Ready-to-build' ? 0.103 : 0.095) + (rnd() - 0.5) * 0.014;
      const band = off ? [2200, 3400] : solar ? [560, 950] : [1050, 1700];
      const capexKw = Math.min(band[1], Math.max(band[0], ebitda1 / yieldTarget / mw / 1000 * 1e6));
      const capex = mw * 1000 * capexKw / 1e6;
      const p = { id: 'P' + String(i + 1).padStart(2, '0'), name, cc, country: names[cc], iso3: iso3[cc], lat, lon, tech, stage, mw, cod, cf, capexKw, opexKw, devRisk, gridSecured, omPartner, ppaShare, ppaPrice, ppaTenor, merchant: capturePrice, baseload: merch[cc], maxGear, capex, ccy: ccy[cc], eur: ccy[cc] === 'EUR' };
      this.model(p);
      return p;
    });
  }

  seeded(s) { let x = s >>> 0 || 1; return () => { x ^= x << 13; x ^= x >>> 17; x ^= x << 5; x >>>= 0; return x / 4294967296; }; }

  // ── project cash-flow model, 30 years from 2027 ─────────────────────────
  model(p) {
    const Y0 = 2027, N = 30, rate = 0.055, tenor = 18;
    const deg = p.tech === 'Solar' ? 0.005 : 0.002;
    const build = Math.max(1, p.cod - Y0);
    // Debt is sculpted to a 1.40× base-case DSCR, then capped by maximum gearing —
    // weaker assets simply carry less leverage rather than being unfinanceable.
    const af = rate / (1 - Math.pow(1 + rate, -tenor));
    const gen1 = p.mw * 8.760 * p.cf * (1 - deg);
    const price1 = p.ppaTenor > 1
      ? p.ppaShare * p.ppaPrice * 1.005 + (1 - p.ppaShare) * p.merchant * 1.021
      : p.merchant * 1.021;
    const ebitda1 = gen1 * 1000 * price1 / 1e6 - p.mw * 1000 * p.opexKw * 1.021 / 1e6;
    p.debt = Math.max(0, Math.min(p.maxGear * p.capex, ebitda1 / 1.40 / af));
    p.lev = p.debt / p.capex;
    p.equity = p.capex - p.debt;
    const ann = p.debt * af;
    const depr = p.capex / 25;
    const eq = [], ebitdaArr = [], genArr = [];
    let outstanding = p.debt;
    for (let t = 0; t < N; t++) {
      const yr = Y0 + t;
      let cf = 0, ebitda = 0, gwh = 0;
      if (yr < p.cod) cf -= p.equity / build;
      else if (t === 0 && p.cod <= Y0) cf -= p.equity;
      if (yr >= p.cod) {
        const age = yr - p.cod;
        gwh = p.mw * 8.760 * p.cf * Math.pow(1 - deg, age) * (age === 0 ? 0.55 : 1);
        const underPpa = p.ppaTenor > 0 && age < p.ppaTenor;
        const price = underPpa
          ? p.ppaShare * p.ppaPrice * Math.pow(1.005, age) + (1 - p.ppaShare) * p.merchant * Math.pow(1.021, age)
          : p.merchant * Math.pow(1.021, age);
        const rev = gwh * 1000 * price / 1e6;
        const opex = p.mw * 1000 * p.opexKw * Math.pow(1.021, age) / 1e6;
        ebitda = rev - opex;
        const interest = age < tenor ? outstanding * rate : 0;
        const principal = age < tenor ? Math.max(0, ann - interest) : 0;
        if (age < tenor) outstanding = Math.max(0, outstanding - principal);
        const taxable = ebitda - interest - (age < 25 ? depr : 0);
        const tax = Math.max(0, taxable * 0.20);
        cf += ebitda - interest - principal - tax;
      }
      eq.push(cf); ebitdaArr.push(ebitda); genArr.push(gwh);
    }
    p.cfEquity = eq; p.ebitda = ebitdaArr; p.gen = genArr;
    p.gwh = p.mw * 8.760 * p.cf;
    // min DSCR over the debt life
    let minD = 99;
    let o = p.debt;
    for (let t = 0; t < N; t++) {
      const yr = Y0 + t, age = yr - p.cod;
      if (age < 0 || age >= tenor) continue;
      const interest = o * rate, principal = Math.max(0, ann - interest);
      o = Math.max(0, o - principal);
      if (age === 0) continue;
      minD = Math.min(minD, ebitdaArr[t] / ann);
    }
    p.dscr = Math.round(Math.min(minD, 3.2) * 100) / 100;
    // LCOE, 6% real
    let pvC = p.capex, pvG = 0;
    for (let t = 0; t < N; t++) {
      const d = Math.pow(1.06, t + 1), age = Y0 + t - p.cod;
      if (age >= 0) { pvC += p.mw * 1000 * p.opexKw / 1e6 / d; pvG += genArr[t] * 1000 / d; }
    }
    p.lcoe = pvG > 0 ? Math.round(pvC * 1e6 / pvG) : 0;
    p.irr30 = this.irr(eq);
  }

  irr(cf) {
    const npv = (r) => cf.reduce((a, c, i) => a + c / Math.pow(1 + r, i + 1), 0);
    let lo = -0.5, hi = 1.2;
    if (npv(lo) * npv(hi) > 0) return null;
    for (let i = 0; i < 70; i++) { const m = (lo + hi) / 2; if (npv(lo) * npv(m) <= 0) hi = m; else lo = m; }
    return (lo + hi) / 2;
  }

  holdCf(p, hold) {
    const exit = Math.min(hold, 30);
    const cf = p.cfEquity.slice(0, exit).slice();
    const base = this.props.exitMultiple ?? 9;
    const mult = p.tech === 'Solar' ? base : p.tech === 'Wind' ? base - 0.5 : base + 0.5;
    const ebitdaExit = p.ebitda[exit - 1] || 0;
    let o = p.debt, ann = p.debt * 0.055 / (1 - Math.pow(1.055, -18));
    for (let t = 0; t < exit; t++) { const age = 2027 + t - p.cod; if (age >= 0 && age < 18) { const int = o * 0.055; o = Math.max(0, o - Math.max(0, ann - int)); } }
    cf[exit - 1] = (cf[exit - 1] || 0) + Math.max(0, ebitdaExit * mult - o);
    return cf;
  }

  projIrr(p, hold) {
    const key = 'irr' + hold + 'x' + (this.props.exitMultiple ?? 9);
    if (p[key] === undefined) p[key] = this.irr(this.holdCf(p, hold));
    return p[key];
  }

  // ── screening & GA ─────────────────────────────────────────────────────
  eligible(s) {
    const cap = { Low: 2.6, Balanced: 3.6, High: 5 }[s.risk];
    return this.projects.filter(p =>
      s.countries.includes(p.cc) &&
      s.stages.includes(p.stage) &&
      p.cod >= s.codFrom && p.cod <= s.codTo &&
      p.dscr >= s.minDscr &&
      p.devRisk <= cap &&
      (!s.gridOnly || p.gridSecured) &&
      (!s.omOnly || p.omPartner) &&
      (!s.hedged || p.eur) &&
      !s.excluded.includes(p.id));
  }

  aggregate(sel, s) {
    let mw = 0, capex = 0, debt = 0, equity = 0, gwh = 0, solarMw = 0, ppaW = 0, lcoeW = 0, riskW = 0, irrW = 0;
    const byC = {};
    sel.forEach(p => {
      mw += p.mw; capex += p.capex; debt += p.debt; equity += p.equity; gwh += p.gwh;
      if (p.tech === 'Solar') solarMw += p.mw;
      ppaW += p.ppaShare * p.capex; lcoeW += p.lcoe * p.gwh; riskW += p.devRisk * p.capex;
      irrW += (this.projIrr(p, s.hold) || 0) * p.equity;
      byC[p.cc] = (byC[p.cc] || 0) + p.capex;
    });
    return { n: sel.length, mw, capex, debt, equity, gwh, solarMw, byC,
      solarPct: mw ? solarMw / mw : 0, lev: capex ? debt / capex : 0,
      merchant: capex ? 1 - ppaW / capex : 0, lcoe: gwh ? lcoeW / gwh : 0,
      risk: capex ? riskW / capex : 0, irrApprox: equity ? irrW / equity : 0 };
  }

  fitness(genes, pool, s) {
    const sel = []; for (let i = 0; i < pool.length; i++) if (genes[i]) sel.push(pool[i]);
    if (!sel.length) return -50;
    const a = this.aggregate(sel, s);
    if (a.equity > s.capital) return -20 - (a.equity / s.capital);
    let f = 0;
    f += 3.2 * (1 - Math.min(1.6, Math.abs(a.mw - s.target) / s.target));
    f += 3.0 * (1 - Math.min(1.5, Math.abs(a.solarPct - s.solarShare) / 0.35));
    f += 2.6 * Math.max(-1.2, Math.min(1.2, (a.irrApprox - s.hurdle / 100) / 0.05));
    f += 0.9 * (a.equity / s.capital);
    f -= 7 * Math.max(0, s.minLev / 100 - a.lev);
    f -= 14 * Math.max(0, a.merchant - s.maxMerchant / 100);
    f -= 1.6 * Math.max(0, a.risk - ({ Low: 2.4, Balanced: 3.2, High: 4.2 })[s.risk]);
    let cp = 0; Object.keys(a.byC).forEach(c => { cp += Math.max(0, a.byC[c] / a.capex - s.maxCountry / 100); });
    f -= 8 * cp;
    let pp = 0; sel.forEach(p => { pp += Math.max(0, p.capex / a.capex - s.maxProject / 100); });
    f -= 8 * pp;
    return f;
  }

  run = () => {
    const s = this.state;
    const pool = this.eligible(s);
    if (!pool.length) return;
    const effort = { Fast: [50, 35], Standard: [90, 60], Exhaustive: [160, 110] }[this.props.algorithmEffort ?? 'Standard'] || [90, 60];
    const N = pool.length, POP = effort[0], G = effort[1];
    this.setState({ popSize: POP, genTotal: G });
    const lockedIdx = pool.map((p, i) => s.locked.includes(p.id) ? i : -1).filter(i => i >= 0);
    const rnd = this.seeded(Date.now() % 100000);
    const force = g => { lockedIdx.forEach(i => g[i] = 1); return g; };
    let pop = [];
    for (let i = 0; i < POP; i++) pop.push(force(Array.from({ length: N }, () => rnd() < 0.35 ? 1 : 0)));
    this.setState({ screen: 'running', gen: 0, hist: [], best: null, hover: null, dirty: false });

    const step = () => {
      const scored = pop.map(g => ({ g, f: this.fitness(g, pool, s) })).sort((a, b) => b.f - a.f);
      const mean = scored.reduce((a, x) => a + x.f, 0) / scored.length;
      const next = [scored[0].g, scored[1].g];
      const pick = () => { const a = scored[Math.floor(rnd() * POP)], b = scored[Math.floor(rnd() * POP)]; return a.f > b.f ? a.g : b.g; };
      while (next.length < POP) {
        const p1 = pick(), p2 = pick(), c = [];
        for (let i = 0; i < N; i++) { let bit = rnd() < 0.5 ? p1[i] : p2[i]; if (rnd() < 0.025) bit = bit ? 0 : 1; c.push(bit); }
        next.push(force(c));
      }
      pop = next;
      const gen = this.state.gen + 1;
      const hist = this.state.hist.concat([[scored[0].f, mean]]);
      const bestSel = []; for (let i = 0; i < N; i++) if (scored[0].g[i]) bestSel.push(pool[i]);
      if (gen >= G) {
        clearInterval(this._timer);
        const ids = bestSel.map(p => p.id);
        this.setState({ gen, hist, best: { ids, fitness: scored[0].f }, screen: 'results', runRef: 'A-' + (parseInt(String(this.state.runRef).split('-')[1], 10) + 1) });
        this._mapDrawn = false;
      } else {
        this.setState({ gen, hist, best: { ids: bestSel.map(p => p.id), fitness: scored[0].f } });
      }
    };
    clearInterval(this._timer);
    this._timer = setInterval(step, 45);
  };

  componentWillUnmount() { clearInterval(this._timer); }
  componentDidUpdate() { if (this.state.screen === 'results' && !this._mapDrawn) this.drawMap(); }

  // ── map ────────────────────────────────────────────────────────────────
  async drawMap() {
    const el = this._map;
    if (!el || !window.d3 || !window.topojson) { setTimeout(() => { this._mapDrawn = false; this.forceUpdate(); }, 300); return; }
    this._mapDrawn = true;
    try {
      if (!this._topo) {
        const r = await fetch((window.__resources && window.__resources.worldAtlas) || 'https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/countries-110m.json');
        this._topo = await r.json();
      }
      const d3 = window.d3;
      const feats = window.topojson.feature(this._topo, this._topo.objects.countries).features;
      const w = el.clientWidth || 380, h = 300;
      const proj = d3.geoMercator().center([12, 55]).scale(w * 1.15).translate([w / 2, h / 2]);
      const path = d3.geoPath(proj);
      const sel = this.selected();
      const active = new Set(sel.map(p => p.country));
      d3.select(el).selectAll('*').remove();
      const svg = d3.select(el).append('svg').attr('width', w).attr('height', h).style('display', 'block');
      svg.append('g').selectAll('path').data(feats).join('path')
        .attr('d', path)
        .attr('fill', d => active.has(d.properties.name) ? 'var(--color-accent-200)' : 'var(--color-neutral-200)')
        .attr('stroke', 'var(--color-divider)').attr('stroke-width', 0.6);
      svg.append('g').selectAll('circle').data(sel).join('circle')
        .attr('cx', d => proj([d.lon, d.lat])[0]).attr('cy', d => proj([d.lon, d.lat])[1])
        .attr('r', d => Math.max(3, Math.sqrt(d.mw) * 0.42))
        .attr('fill', d => d.tech === 'Solar' ? 'var(--color-accent-700)' : 'var(--color-accent-400)')
        .attr('fill-opacity', 0.82).attr('stroke', 'var(--color-bg)').attr('stroke-width', 1);
    } catch (e) { el.innerHTML = '<div style="font-size:12px;padding:10px;color:#7a7a7d">Map data unavailable offline.</div>'; }
  }

  selected() {
    const ids = this.state.best ? this.state.best.ids : [];
    return this.projects.filter(p => ids.includes(p.id));
  }

  // ── formatting ─────────────────────────────────────────────────────────
  n0(x) { return Math.round(x).toLocaleString('en-GB'); }
  n1(x) { return (Math.round(x * 10) / 10).toLocaleString('en-GB', { minimumFractionDigits: 1, maximumFractionDigits: 1 }); }
  pct(x, d) { return (x * 100).toFixed(d === undefined ? 1 : d) + '%'; }

  set(k) { return e => { const t = e.target; const val = t.type === 'number' || t.type === 'range' ? parseFloat(t.value) : t.value; this.setState({ [k]: val, dirty: true }); }; }

  download(name, text) {
    const b = new Blob([text], { type: 'text/csv' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(b); a.download = name; a.click();
    setTimeout(() => URL.revokeObjectURL(a.href), 2000);
  }

  renderVals() {
    const s = this.state;
    const acc = 'var(--color-accent-700)', mute = 'var(--color-neutral-700)';
    const pool = this.eligible(s);
    const poolMw = this.projects.reduce((a, p) => a + p.mw, 0);
    const elig = this.aggregate(pool, s);
    const chipBase = 'tag tag-outline', chipOn = 'tag tag-accent';

    const h = {
      capital: this.set('capital'), target: this.set('target'), hurdle: this.set('hurdle'),
      hold: this.set('hold'), minLev: this.set('minLev'), minDscr: this.set('minDscr'),
      maxMerchant: this.set('maxMerchant'), maxCountry: this.set('maxCountry'), maxProject: this.set('maxProject'),
      codFrom: this.set('codFrom'), codTo: this.set('codTo'),
      q: this.set('q'), fCountry: this.set('fCountry'), fTech: this.set('fTech'), fStage: this.set('fStage'),
      solarShare: e => this.setState({ solarShare: parseFloat(e.target.value) / 100, dirty: true }),
      allCountries: () => this.setState({ countries: s.countries.length === 14 ? [] : ['ES','PT','IT','GR','FR','DE','PL','RO','NL','DK','IE','SE','FI','UK'], dirty: true }),
      run: this.run,
      rerun: this.run,
      back: () => this.setState({ screen: 'input' }),
      unhover: () => this.setState({ hover: null }),
      closeDrawer: () => this.setState({ drawer: null }),
      openExport: () => this.setState({ exportOpen: true }),
      closeExport: () => this.setState({ exportOpen: false }),
      stop: e => e.stopPropagation(),
      toggleShowAll: () => this.setState({ showAll: !s.showAll }),
      print: () => window.print(),
      drawerLock: () => { const id = s.drawer; this.setState({ locked: s.locked.includes(id) ? s.locked.filter(x => x !== id) : s.locked.concat([id]), dirty: true }); },
      drawerExclude: () => { const id = s.drawer; this.setState({ excluded: s.excluded.includes(id) ? s.excluded.filter(x => x !== id) : s.excluded.concat([id]), locked: s.locked.filter(x => x !== id), dirty: true, drawer: null }); }
    };

    const v = {
      capital: s.capital, target: s.target, hurdle: s.hurdle, hold: s.hold, exitYear: 2027 + s.hold,
      capitalLabel: this.n0(s.capital), targetLabel: this.n0(s.target),
      solarPct: Math.round(s.solarShare * 100), windPct: 100 - Math.round(s.solarShare * 100),
      minLev: s.minLev, minDscr: s.minDscr, maxMerchant: s.maxMerchant, maxCountry: s.maxCountry,
      maxProject: s.maxProject, codFrom: s.codFrom, codTo: s.codTo, q: s.q,
      fCountry: s.fCountry, fTech: s.fTech, fStage: s.fStage, exportOpen: s.exportOpen
    };

    const ccList = ['ES','PT','IT','GR','FR','DE','PL','RO','NL','DK','IE','SE','FI','UK'];
    const flag = c => String.fromCodePoint(...(c === 'UK' ? 'GB' : c).split('').map(x => 127397 + x.charCodeAt(0)));
    const cName = {};
    this.projects.forEach(p => { cName[p.cc] = p.country; });
    const countryChips = ccList.map(c => ({
      label: flag(c) + '  ' + cName[c], cls: s.countries.includes(c) ? chipOn : chipBase,
      toggle: () => this.setState({ countries: s.countries.includes(c) ? s.countries.filter(x => x !== c) : s.countries.concat([c]), dirty: true })
    }));
    const stageChips = ['Greenfield','Ready-to-build','Construction'].map(st => ({
      label: st, cls: s.stages.includes(st) ? chipOn : chipBase,
      toggle: () => this.setState({ stages: s.stages.includes(st) ? s.stages.filter(x => x !== st) : s.stages.concat([st]), dirty: true })
    }));
    const riskOptions = ['Low','Balanced','High'].map(r => ({
      label: r, checked: s.risk === r,
      pick: () => this.setState({ risk: r, dirty: true })
    }));
    const riskNote = { Low: 'Excludes anything above risk score 2.6 — mostly RTB and construction assets.', Balanced: 'Admits development assets up to risk score 3.6.', High: 'Full pipeline, including early-stage greenfield.' }[s.risk];

    const toggles = [
      { key: 'gridOnly', label: 'Grid connection secured only', note: 'Drops projects without a firm connection agreement' },
      { key: 'hedged', label: 'EUR-denominated revenue only', note: 'Excludes PLN, RON, DKK, SEK and GBP exposure' },
      { key: 'omOnly', label: 'O&M partner contracted', note: 'Requires a signed long-term service agreement' }
    ].map(t => ({
      label: t.label, note: t.note,
      trackBg: s[t.key] ? 'var(--color-accent)' : 'transparent',
      knobBg: s[t.key] ? 'var(--color-bg)' : 'var(--color-neutral-400)',
      knobLeft: s[t.key] ? '24px' : '2px',
      flip: () => this.setState({ [t.key]: !s[t.key], dirty: true })
    }));

    const warnings = [];
    if (!pool.length) warnings.push({ mark: '×', text: 'No candidates pass the current screens. Widen countries, stages or the COD window.', color: 'var(--color-accent-800)' });
    if (pool.length && elig.mw < s.target) warnings.push({ mark: '!', text: 'Eligible pipeline is ' + this.n0(elig.mw) + ' MW — below the ' + this.n0(s.target) + ' MW target.', color: 'var(--color-accent-800)' });
    if (pool.length && elig.equity < s.capital * 0.9 && elig.mw >= s.target) warnings.push({ mark: '!', text: 'Full pipeline absorbs only €' + this.n0(elig.equity) + 'm of the €' + this.n0(s.capital) + 'm available.', color: mute });
    if (pool.length && elig.solarPct < s.solarShare - 0.2) warnings.push({ mark: '!', text: 'Solar target of ' + Math.round(s.solarShare * 100) + '% may be unreachable: eligible pool is ' + Math.round(elig.solarPct * 100) + '% solar.', color: mute });
    if (pool.length && elig.lev < s.minLev / 100) warnings.push({ mark: '!', text: 'Minimum leverage of ' + s.minLev + '% exceeds what the eligible pool supports (' + Math.round(elig.lev * 100) + '%).', color: 'var(--color-accent-800)' });
    if (s.locked.length) warnings.push({ mark: '•', text: s.locked.length + ' project(s) locked in; ' + s.excluded.length + ' excluded.', color: mute });

    // running screen
    const hist = s.hist;
    const maxF = Math.max(1, ...hist.map(x => x[0]));
    const minF = Math.min(0, ...hist.map(x => x[1]));
    const pt = (arr, idx) => arr.map((x, i) => {
      const px = hist.length > 1 ? (i / (s.genTotal - 1)) * 600 : 0;
      const py = 150 - ((x[idx] - minF) / Math.max(0.001, maxF - minF)) * 140 - 5;
      return px.toFixed(1) + ',' + py.toFixed(1);
    }).join(' ');
    const liveBest = s.best ? this.aggregate(this.projects.filter(p => s.best.ids.includes(p.id)), s) : null;
    const liveStats = [
      { label: 'Best fitness', value: s.best ? s.best.fitness.toFixed(3) : '—' },
      { label: 'Capacity', value: liveBest ? this.n0(liveBest.mw) + ' MW' : '—' },
      { label: 'Projects', value: liveBest ? String(liveBest.n) : '—' },
      { label: 'Equity drawn', value: liveBest ? '€' + this.n0(liveBest.equity) + 'm' : '—' },
      { label: 'Blended IRR', value: liveBest ? this.pct(liveBest.irrApprox) : '—' }
    ];

    // results
    const sel = this.selected();
    const agg = sel.length ? this.aggregate(sel, s) : null;
    let tiles = [], bars = [], cumFcf = '—', axisTop = '', axisBottom = '', zeroLine = '50%', portIrr = null, moic = null, fcf = [];
    if (agg) {
      fcf = Array.from({ length: 30 }, (_, t) => sel.reduce((a, p) => a + p.cfEquity[t], 0));
      const holdCf = sel.reduce((acc2, p) => { const c = this.holdCf(p, s.hold); c.forEach((x, i) => acc2[i] = (acc2[i] || 0) + x); return acc2; }, []);
      portIrr = this.irr(holdCf);
      const inflow = holdCf.reduce((a, x) => a + Math.max(0, x), 0), outflow = -holdCf.reduce((a, x) => a + Math.min(0, x), 0);
      moic = outflow > 0 ? inflow / outflow : 0;
      const cum = fcf.reduce((a, x) => a + x, 0);
      cumFcf = this.n0(cum);
      const hi = Math.max(...fcf, 0), lo = Math.min(...fcf, 0), span = hi - lo || 1;
      const zeroPct = (hi / span) * 100;
      zeroLine = zeroPct.toFixed(1) + '%';
      axisTop = '€' + this.n0(hi) + 'm'; axisBottom = '€' + this.n0(lo) + 'm';
      bars = fcf.map((x, i) => {
        const yr = 2027 + i;
        const hPct = Math.abs(x) / span * 100;
        return {
          tick: i % 5 === 0 ? String(yr) : '',
          top: (x >= 0 ? zeroPct - hPct : zeroPct).toFixed(2) + '%',
          h: Math.max(0.4, hPct).toFixed(2) + '%',
          bg: x >= 0 ? (s.hover === i ? 'var(--color-accent-800)' : 'var(--color-accent)') : 'var(--color-accent-300)',
          hover: () => this.setState({ hover: i })
        };
      });
      const wind = sel.filter(p => p.tech !== 'Solar').length;
      const conc = Math.max(...Object.keys(agg.byC).map(c => agg.byC[c] / agg.capex));
      const worstD = Math.min(...sel.map(p => p.dscr));
      tiles = [
        { label: 'Installed capacity', value: this.n0(agg.mw) + ' MW', sub: 'target ' + this.n0(s.target) + ' MW', subColor: Math.abs(agg.mw - s.target) / s.target < 0.08 ? acc : mute, bg: 'transparent' },
        { label: 'Projects', value: String(agg.n), sub: (agg.n - wind) + ' solar · ' + wind + ' wind', subColor: mute, bg: 'transparent' },
        { label: 'Technology split', value: this.pct(agg.solarPct, 0) + ' solar', sub: 'target ' + Math.round(s.solarShare * 100) + '% solar', subColor: Math.abs(agg.solarPct - s.solarShare) < 0.08 ? acc : mute, bg: 'transparent' },
        { label: 'Equity required', value: '€' + this.n0(agg.equity) + 'm', sub: 'of €' + this.n0(s.capital) + 'm · ' + this.pct(agg.equity / s.capital, 0) + ' deployed', subColor: mute, bg: 'transparent' },
        { label: 'Total project cost', value: '€' + this.n0(agg.capex) + 'm', sub: '€' + this.n0(agg.debt) + 'm senior debt', subColor: mute, bg: 'transparent' },
        { label: 'Equity IRR (' + s.hold + 'y)', value: portIrr === null ? '—' : this.pct(portIrr), sub: 'hurdle ' + s.hurdle + '% · ' + (moic ? moic.toFixed(2) + '× MOIC' : ''), subColor: portIrr !== null && portIrr >= s.hurdle / 100 ? acc : 'var(--color-accent-800)', bg: 'var(--color-accent-100)' },
        { label: 'Leverage', value: this.pct(agg.lev, 0), sub: 'min ' + s.minLev + '% · DSCR floor ' + worstD.toFixed(2) + '×', subColor: agg.lev >= s.minLev / 100 ? mute : 'var(--color-accent-800)', bg: 'transparent' },
        { label: 'Weighted LCOE', value: '€' + this.n0(agg.lcoe), sub: 'per MWh, 6% real', subColor: mute, bg: 'transparent' },
        { label: 'Annual generation', value: this.n0(agg.gwh) + ' GWh', sub: this.n0(agg.gwh * 1000 * 0.32 / 1000) + ' kt CO₂ avoided p.a.', subColor: mute, bg: 'transparent' },
        { label: '30-year FCFE', value: '€' + this.n0(fcf.reduce((a, x) => a + x, 0)) + 'm', sub: 'undiscounted, post debt', subColor: mute, bg: 'transparent' },
        { label: 'Merchant exposure', value: this.pct(agg.merchant, 0), sub: 'cap ' + s.maxMerchant + '%', subColor: agg.merchant <= s.maxMerchant / 100 ? mute : 'var(--color-accent-800)', bg: 'transparent' },
        { label: 'Largest country', value: this.pct(conc, 0), sub: 'cap ' + s.maxCountry + '% · risk score ' + agg.risk.toFixed(1), subColor: conc <= s.maxCountry / 100 ? mute : 'var(--color-accent-800)', bg: 'transparent' }
      ];
    }

    // table
    const base = s.showAll ? pool : sel;
    let rows = base.filter(p =>
      (s.fCountry === 'All' || p.country === s.fCountry) &&
      (s.fTech === 'All' || p.tech === s.fTech) &&
      (s.fStage === 'All' || p.stage === s.fStage) &&
      (!s.q || (p.name + ' ' + p.country).toLowerCase().includes(String(s.q).toLowerCase())));
    const key = s.sortKey;
    const val = p => ({ name: p.name, country: p.country, tech: p.tech, stage: p.stage, mw: p.mw, cod: p.cod,
      capex: p.capex, equity: p.equity, lev: p.lev, cf: p.cf, gwh: p.gwh, lcoe: p.lcoe,
      offtake: p.ppaShare, irr: this.projIrr(p, s.hold) || 0, dscr: p.dscr, risk: p.devRisk }[key]);
    rows = rows.slice().sort((a, b) => { const x = val(a), y = val(b); return (typeof x === 'string' ? x.localeCompare(y) : x - y) * s.sortDir; });

    const columns = [
      { key: 'lock', label: '', align: 'left' }, { key: 'name', label: 'Project', align: 'left' },
      { key: 'tech', label: 'Technology', align: 'left' }, { key: 'stage', label: 'Stage', align: 'left' },
      { key: 'mw', label: 'MW', align: 'right' }, { key: 'cod', label: 'COD', align: 'right' },
      { key: 'capex', label: 'Capex €m', align: 'right' }, { key: 'equity', label: 'Equity €m', align: 'right' },
      { key: 'lev', label: 'Lev', align: 'right' }, { key: 'cf', label: 'Cap. factor', align: 'right' },
      { key: 'gwh', label: 'P50 GWh/y', align: 'right' }, { key: 'lcoe', label: 'LCOE €/MWh', align: 'right' },
      { key: 'offtake', label: 'Contracted', align: 'right' }, { key: 'irr', label: 'Equity IRR', align: 'right' },
      { key: 'dscr', label: 'Min DSCR', align: 'right' }, { key: 'risk', label: 'Risk', align: 'right' }
    ].map(c => ({
      label: c.label, align: c.align,
      arrow: s.sortKey === c.key ? (s.sortDir === 1 ? ' ↑' : ' ↓') : '',
      sort: () => { if (c.key === 'lock') return; this.setState({ sortKey: c.key, sortDir: s.sortKey === c.key ? -s.sortDir : -1 }); }
    }));

    const selIds = sel.map(p => p.id);
    const rowVals = rows.map(p => ({
      name: p.name, country: p.country + ' · ' + p.id, tech: p.tech, stage: p.stage,
      mw: this.n0(p.mw), cod: String(p.cod), capex: this.n0(p.capex), equity: this.n0(p.equity),
      lev: this.pct(p.lev, 0), cf: this.pct(p.cf, 1), gwh: this.n0(p.gwh), lcoe: this.n0(p.lcoe),
      offtake: this.pct(p.ppaShare, 0), irr: this.pct(this.projIrr(p, s.hold) || 0),
      dscr: p.dscr.toFixed(2) + '×', dscrColor: p.dscr < s.minDscr ? 'var(--color-accent-800)' : 'inherit',
      risk: p.devRisk.toFixed(1),
      bg: s.locked.includes(p.id) ? 'var(--color-accent-100)' : (selIds.includes(p.id) ? 'transparent' : 'var(--color-neutral-200)'),
      lockMark: s.locked.includes(p.id) ? '■' : '□',
      lockColor: s.locked.includes(p.id) ? 'var(--color-accent-700)' : 'var(--color-neutral-500)',
      open: () => this.setState({ drawer: p.id }),
      toggleLock: e => { e.stopPropagation(); this.setState({ locked: s.locked.includes(p.id) ? s.locked.filter(x => x !== p.id) : s.locked.concat([p.id]), dirty: true }); }
    }));

    // drawer
    let d = null;
    if (s.drawer) {
      const p = this.projects.find(x => x.id === s.drawer);
      if (p) {
        const irr = this.projIrr(p, s.hold) || 0;
        const hc = this.holdCf(p, s.hold);
        const inf = hc.reduce((a, x) => a + Math.max(0, x), 0), outf = -hc.reduce((a, x) => a + Math.min(0, x), 0);
        const pay = p.cfEquity.reduce((acc2, x, i) => { if (acc2.done) return acc2; acc2.sum += x; if (acc2.sum >= 0 && i > 2) { acc2.done = true; acc2.yr = 2027 + i; } return acc2; }, { sum: 0, done: false, yr: null });
        d = {
          name: p.name, tech: p.tech, stage: p.stage,
          location: p.country + ' · ' + p.lat.toFixed(2) + '°, ' + p.lon.toFixed(2) + '° · ' + p.id,
          headline: [
            { label: 'Capacity', value: this.n0(p.mw) + ' MW' },
            { label: 'Equity IRR (' + s.hold + 'y)', value: this.pct(irr) },
            { label: 'Equity', value: '€' + this.n0(p.equity) + 'm' },
            { label: 'MOIC', value: (outf > 0 ? inf / outf : 0).toFixed(2) + '×' }
          ],
          groups: [
            { title: 'Technical', rows: [
              { k: 'Net capacity factor', val: this.pct(p.cf, 1) },
              { k: 'P50 generation', val: this.n0(p.gwh) + ' GWh/yr' },
              { k: 'Commercial operation', val: String(p.cod) },
              { k: 'Grid connection', val: p.gridSecured ? 'Secured' : 'Application pending' },
              { k: 'O&M', val: p.omPartner ? 'Long-term service agreement signed' : 'Not contracted' }
            ] },
            { title: 'Capital structure', rows: [
              { k: 'Total project cost', val: '€' + this.n0(p.capex) + 'm (€' + this.n0(p.capexKw) + '/kW)' },
              { k: 'Senior debt', val: '€' + this.n0(p.debt) + 'm at ' + this.pct(p.lev, 0) + ', 5.5%, 18y' },
              { k: 'Minimum DSCR', val: p.dscr.toFixed(2) + '×' },
              { k: 'Equity payback', val: pay.yr ? String(pay.yr) : 'beyond 2056' },
              { k: 'Currency', val: p.ccy + (p.eur ? '' : ' — hedge required') }
            ] },
            { title: 'Revenue', rows: [
              { k: 'Contracted share', val: this.pct(p.ppaShare, 0) },
              { k: 'PPA price', val: p.ppaTenor ? '€' + p.ppaPrice + '/MWh for ' + p.ppaTenor + ' yrs' : 'merchant only' },
              { k: 'Capture price', val: '€' + p.merchant + '/MWh (baseload €' + p.baseload + ')' },
              { k: 'LCOE', val: '€' + this.n0(p.lcoe) + '/MWh' },
              { k: 'Opex', val: '€' + p.opexKw.toFixed(0) + '/kW/yr' }
            ] },
            { title: 'Risk', rows: [
              { k: 'Development risk score', val: p.devRisk.toFixed(1) + ' / 5' },
              { k: 'Status in portfolio', val: selIds.includes(p.id) ? 'Selected' : (s.excluded.includes(p.id) ? 'Excluded' : 'Not selected') },
              { k: 'Locked', val: s.locked.includes(p.id) ? 'Yes — forced into next run' : 'No' }
            ] }
          ],
          lockLabel: s.locked.includes(p.id) ? 'Unlock' : 'Lock into portfolio',
          excludeLabel: s.excluded.includes(p.id) ? 'Re-admit candidate' : 'Exclude from search'
        };
      }
    }

    h.exportCsv = () => {
      const head = 'ID,Project,Country,Technology,Stage,MW,COD,Capex EURm,Equity EURm,Leverage,Capacity factor,P50 GWh,LCOE EUR/MWh,Contracted share,Equity IRR,Min DSCR,Risk\n';
      const body = sel.map(p => [p.id, p.name, p.country, p.tech, p.stage, p.mw, p.cod, p.capex.toFixed(1), p.equity.toFixed(1), (p.lev * 100).toFixed(0) + '%', (p.cf * 100).toFixed(1) + '%', p.gwh.toFixed(0), p.lcoe, (p.ppaShare * 100).toFixed(0) + '%', ((this.projIrr(p, s.hold) || 0) * 100).toFixed(1) + '%', p.dscr.toFixed(2), p.devRisk].join(',')).join('\n');
      this.download('portfolio-holdings.csv', head + body);
    };
    h.exportCashflow = () => {
      const body = 'Year,FCFE EURm\n' + fcf.map((x, i) => (2027 + i) + ',' + x.toFixed(2)).join('\n');
      this.download('portfolio-cashflow.csv', body);
    };

    const hoverLabel = s.hover !== null && fcf.length ? (2027 + s.hover) + ': €' + this.n1(fcf[s.hover]) + 'm' : 'hover a bar';

    return {
      isInput: s.screen === 'input', isRunning: s.screen === 'running', isResults: s.screen === 'results',
      stepColor1: s.screen === 'input' ? acc : mute,
      stepColor2: s.screen === 'running' ? acc : mute,
      stepColor3: s.screen === 'results' ? acc : mute,
      v, h, countryChips, stageChips, riskOptions, riskNote, toggles, warnings,
      countryToggleLabel: s.countries.length === 14 ? 'Clear all' : 'Select all',
      toggleHover: { background: 'color-mix(in srgb, var(--color-text) 5%, transparent)' },
      poolCount: this.projects.length, poolMw: this.n0(poolMw),
      eligibleCount: pool.length, eligibleMw: this.n0(elig.mw), eligibleEquity: this.n0(elig.equity),
      runDisabled: pool.length === 0,
      popSize: s.popSize, genTotal: s.genTotal, genLabel: String(s.gen).padStart(2, '0'),
      progressPct: Math.round(s.gen / s.genTotal * 100) + '%',
      curveBest: pt(hist, 0), curveAvg: pt(hist, 1), liveStats,
      logLine: s.gen < 8 ? 'seeding population · evaluating constraint feasibility' : s.gen < 30 ? 'crossover and mutation · pruning infeasible portfolios' : 'converging on elite solution · computing levered returns',
      tiles, bars, cumFcf, axisTop, axisBottom, zeroLine, hoverLabel,
      mapDisplay: (this.props.showMap ?? true) ? 'block' : 'none',
      mapRef: el => { this._map = el; },
      resultSubtitle: agg ? this.n0(agg.mw) + ' MW across ' + agg.n + ' projects in ' + Object.keys(agg.byC).length + ' countries · ' + s.hold + '-year hold · run ' + s.runRef : '',
      rerunLabel: s.dirty ? 'Re-run with changes' : 'Re-run',
      columns, rows: rowVals,
      tableCountLabel: rowVals.length + ' of ' + (s.showAll ? pool.length + ' eligible candidates' : sel.length + ' selected'),
      showAllCls: s.showAll ? 'tag tag-accent' : 'tag tag-outline',
      showAllLabel: s.showAll ? 'Showing all candidates' : 'Show all candidates',
      countryOptions: ['All'].concat(Array.from(new Set(base.map(p => p.country))).sort()).map(x => ({ value: x, label: x === 'All' ? 'All countries' : x })),
      techOptions: ['All','Solar','Wind','Offshore wind'].map(x => ({ value: x, label: x === 'All' ? 'All technologies' : x })),
      stageOptions: ['All','Greenfield','Ready-to-build','Construction'].map(x => ({ value: x, label: x === 'All' ? 'All stages' : x })),
      drawerOpen: !!d, d: d || { headline: [], groups: [] },
      runRef: s.runRef, exportRowCount: sel.length
    };
  }
};
}
