// GENERATED by tools/extract_reference.mjs — do not edit.
//
// Minimal host for the extracted reference component.  The reference's render
// methods are never invoked, so no DOM or React shim is needed — only
// `this.props` (the model reads the exit multiple from it) and a synchronous
// `setState` (run() reads back `this.state.gen` and `this.state.hist`
// between GA generations).
//
// Regenerate with: node tools/extract_reference.mjs

import { defineComponent } from './component.mjs';

class DCLogic {
  constructor(props) {
    this.props = props;
    this.state = {};
  }

  // React's setState is asynchronous, but the reference's GA only reads state
  // between ticks, which is exactly what a synchronous shallow merge gives.
  setState(patch) {
    this.state = { ...this.state, ...(typeof patch === 'function' ? patch(this.state) : patch) };
  }

  forceUpdate() {}
}

export const DEFAULT_PROPS = Object.freeze({ algorithmEffort: 'Standard', exitMultiple: 9 });

/**
 * Build a fresh reference instance.  Always prefer a fresh instance over
 * mutating `props` on an existing one: projIrr() memoises onto the project
 * objects, and a fresh instance keeps those caches from crossing runs.
 *
 * The returned object carries a `__timer` handle holding the GA step function
 * that run() scheduled, and a `__stopped` flag set when run() calls
 * clearInterval.  driveGa() below uses both to pump the loop.
 */
export function createReference(props = DEFAULT_PROPS) {
  const timer = { step: null, stopped: false };
  const setInterval = (fn) => { timer.step = fn; timer.stopped = false; return 1; };
  const clearInterval = () => { timer.stopped = true; };
  const Component = defineComponent(DCLogic, setInterval, clearInterval);
  const instance = new Component({ ...DEFAULT_PROPS, ...props });
  instance.__timer = timer;
  return instance;
}

/**
 * Run the reference's OWN genetic algorithm to completion, deterministically.
 *
 * Two things stand between run() and a reproducible trace: it seeds from
 * `Date.now()`, and it advances on a 45 ms timer.  We replace the first by
 * overriding `seeded` on the instance AFTER construction (so buildPipeline has
 * already drawn its real per-project streams), and the second by pumping the
 * captured step function ourselves.  The reference's GA source is not touched.
 *
 * @param {object} instance from createReference()
 * @param {object} mandate  merged over the reference's default state
 * @param {number} seed     the PRNG seed to force in place of Date.now()
 * @param {Function} onGeneration called with the instance after each generation
 */
export function driveGa(instance, mandate, seed, onGeneration) {
  instance.setState({ ...instance.state, ...mandate });
  const seeded = Object.getPrototypeOf(instance).seeded;
  instance.seeded = () => seeded.call(instance, seed);

  instance.run();
  if (typeof instance.__timer.step !== 'function') {
    throw new Error('run() did not schedule a GA step — the reference has changed shape');
  }

  let guard = 0;
  while (!instance.__timer.stopped) {
    instance.__timer.step();
    if (onGeneration) onGeneration(instance);
    if (++guard > 100000) throw new Error('GA did not terminate');
  }
  return instance.state;
}
